### ISSUE TITLE
Дай добро на включение содержания этого репозитория в дымовые тесты Ванесса-АДД

### ISSUE THREAD

**Issue by artbear** [SidnevAV/SmokeTests1C#8]
@SidnevAV я буквально только что увидел увидел этот твой репозиторий.

Очень замечательно ты оформил его и документировал.

Пожалуйста, Дай добро на включение содержания этого репозитория в дымовые тесты Ванесса-АДД

фактически твой ПР https://github.com/vanessa-opensource/add/pull/762 уже включает исходники тестов, но вот документации и примеров настроек не хватает.

- я бы добавил доку + примеры в каталог smoke
- в лицензиях также указал бы ссылку на твой репозиторий

жду ответа.

PS ты вообще как? с лета у тебя нет коммитов на гитхабе (
все в порядке?
я на этот репо и набрел, потому что хотел посмотреть твою активность, т.к. ты молчишь длительное время.

**Comment by SidnevAV** [comment]
@artbear Добро даю. У меня есть еще наработки по дымовым тестам на работе, в ближайшее время закину в гитхаб.
